Models/Pets.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Shelter2.Models
{
    public class Pets
    {
        public int Id { get; set; }
        [Display(Name = "Имя")]

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string? Name { get; set; }
        [Display(Name = "Дата")]
        [DataType(DataType.Date)]

        public DateTime Date { get; set; }
        [Display(Name = "Тип операции")]
        [RegularExpression(@"^[А-Я]+[а-яА-Я\s]*$")]
        [Required]
        [StringLength(30)]
        public string? TypeOfInspection { get; set; }

        [Range(1, 3000)]
        [DataType(DataType.Currency)]
        [Precision(18, 2)]

        [Display(Name = "Возраст")]
        public decimal Price { get; set; }

        [Range(1, 100)]
        [Display(Name = "Цена")]
        public int Age { get; set; }
        [Display(Name = "Приют")]
        public int? ShelterId { get; set; }
        [Display(Name = "Приют")]
        public Shelter? Shelter { get; set; }
    }
}

Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shelter2.Data;
using Shelter2.Models;

namespace Shelter2.Controllers
{
    public class PetsController : Controller
    {
        private readonly Shelter2Context _context;

        public PetsController(Shelter2Context context)
        {
            _context = context;
        }

        // GET: Pets
        public async Task<IActionResult> Index(string PetsTypeOfInspection, string SearchString)
        {
            {
                if (_context.Pets == null)
                {
                    return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
                }
                IQueryable<string> typeQuery = from m in _context.Pets
                                                orderby m.TypeOfInspection
                                                select m.TypeOfInspection;

                var pets = from m in _context.Pets
                             select m;

                if (!String.IsNullOrEmpty(SearchString))
                {
                    pets = pets.Where(s => s.Name!.ToUpper().Contains(SearchString.ToUpper()));
                }

                if (!string.IsNullOrEmpty(PetsTypeOfInspection))
                {
                    pets = pets.Where(x => x.TypeOfInspection == PetsTypeOfInspection);
                }

                var petsTypeVM = new PetsOperationViewModel
                {
                    TypeOfInspection = new SelectList(await typeQuery.Distinct().ToListAsync()),
                    Pets = await pets.ToListAsync()
                };

                return View(petsTypeVM);
            }
        }
        // GET: Pets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pets = await _context.Pets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pets == null)
            {
                return NotFound();
            }

            return View(pets);
        }

        // GET: Pets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Date,TypeOfInspection,Price")] Pets pets)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pets);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pets);
        }

        // GET: Pets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pets = await _context.Pets.FindAsync(id);
            if (pets == null)
            {
                return NotFound();
            }
            return View(pets);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Date,TypeOfInspection,Price,Age")] Pets pets)
        {
            if (id != pets.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pets);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetsExists(pets.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pets);
        }

        // GET: Pets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pets = await _context.Pets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pets == null)
            {
                return NotFound();
            }

            return View(pets);
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pets = await _context.Pets.FindAsync(id);
            if (pets != null)
            {
                _context.Pets.Remove(pets);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PetsExists(int id)
        {
            return _context.Pets.Any(e => e.Id == id);
        }
    }
}

Views/Pets/Create.cshtml
@model Shelter2.Models.Pets

@{
    ViewData["Title"] = "Создать";
}

<h1>Создать</h1>

<h4>Питомцы</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfInspection" class="control-label"></label>
                <input asp-for="TypeOfInspection" class="form-control" />
                <span asp-validation-for="TypeOfInspection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShelterId" class="control-label"></label>
                <select asp-for="ShelterId" class="form-control" asp-items="ViewBag.ShelterId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pets/Delete.cshtml
@model Shelter2.Models.Pets

@{
    ViewData["Title"] = "Удалить";
}

<h1>Удалить</h1>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Питомцы</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfInspection)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfInspection)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

Views/Pets/Details.cshtml
@model Shelter2.Models.Pets

@{
    ViewData["Title"] = "Детались";
}

<h1>Детали</h1>

<div>
    <h4>Питомец</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfInspection)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfInspection)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Изменить</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

Views/Pets/Edit.cshtml
@model Shelter2.Models.Pets

@{
    ViewData["Title"] = "Изменить";
}

<h1>Изменить</h1>

<h4>Питомец</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfInspection" class="control-label"></label>
                <input asp-for="TypeOfInspection" class="form-control" />
                <span asp-validation-for="TypeOfInspection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShelterId" class="control-label"></label>
                <select asp-for="ShelterId" class="form-control" asp-items="ViewBag.ShelterId"></select>
                <span asp-validation-for="ShelterId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Изменить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pets/Index.cshtml
@model Shelter2.Models.PetsOperationViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Питомцы</h1>

<p>
    <a asp-action="Create">Создать нового</a>
</p>


<form asp-controller="Pets" asp-action="Index" method="get">
    <p>
        <select asp-for="PetsTypeOfInspection" asp-items="Model.TypeOfInspection">
            <option value="">All</option>
        </select>

        <label>Имя: <input type="text" name="SearchString" /></label>
        <input type="submit" value="Найти" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pets![0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets![0].Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets![0].TypeOfInspection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets![0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets![0].Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets![0].Shelter)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Pets!)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfInspection)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shelter.NameShelter)
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>